spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/boot_shiro?characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      maxActive: 20
  profiles:
    active: dev
    include: redis